config/routes.rb
Rails.application.routes.draw do
  
  get 'events/new'

  get 'events/create'

  get 'events/index'

  get 'events/show'

  get 'sessions/new'

  resources :users, only: [:new, :create, :show]
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  post '/register/:id', to: 'event_attendings#register', as: 'register'

  root 'sessions#new'
  
  resources :events, only: [:index, :new, :create, :show]
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :event_attendings, :foreign_key => :event_id  
  has_many :attendees, :through => :event_attendings, :source => :attendee
  
  scope :happened_before, -> { where('date < ?', DateTime.now) }
  scope :happens_later, -> {where('date >= ?', DateTime.now)}
  
  # Class methods for getting past and future events
  def Event.past    
    Event.happened_before
  end
  
  def Event.upcoming
    Event.happens_later
  end
   
end

app/models/event_attending.rb
class EventAttending < ActiveRecord::Base
  belongs_to :attendee, :class_name => "User"
  belongs_to :event
end

app/models/user.rb
#include ActionView::Helpers

class User < ActiveRecord::Base
  has_many :events  
  has_many :event_attendings, :foreign_key => :attendee_id
  has_many :attended_events, :through => :event_attendings, :source => :event
      
  def upcoming_events    
    self.attended_events.happens_later    
  end
  
  def previous_events    
    self.attended_events.happened_before
  end  
  
=begin
  def subscribeTo(event_id)
    if !current_user.isSubscribedTo(event_id)
      current_user.event_attendings.build(event_id: event_id).save
    end
  end
  
  def isSubscribedTo?(event_id)
    (current_user.event_attendings.pluck(:event_id).include?event_id)? true : false
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def register
    isRegistered = (current_user.event_attendings.pluck(:event_id).include?params[:id].to_i)? true : false    
    if (!isRegistered)
      if (current_user.event_attendings.build(event_id: params[:id]).save)
        redirect_to user_path(current_user)
        # flash - updated
      else
         #flash - failed to save
      end
    else
      redirect_to events_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create    
    @event = current_user.events.build(event_params)    
    if (@event.save)
      redirect_to @event
    else
      render 'new'
    end
  end

  def index
    @events = Event.all
    @pastEvents = Event.past
    @upcomingEvents = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
    @creator = @event.creator
    @attendees = @event.attendees
  end
  
  private
    def event_params
      params.require(:event).permit(:name, :location, :description, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  helper_method :current_user
  
  def new
  end
  
  def create    
    user = User.find(params[:session][:id])
    if user
      log_in user
      redirect_to user
    else
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if (@user.save)
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    current_user.upcoming_events
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email)  
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper    
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def selectRandomUser
    randomUser = nil
    loop do 
      randomUser = User.all.sample
      break if (randomUser != current_user)
    end
    randomUser
  end
end

app/views/events/_event.html.erb
<div class="<%= "event" %>">
  <div>
    <div class="event-date"><%= event.date.strftime("%b %e, %Y %T") %></div>
    <div class="event-name"><%= event.name %> (Hosted by <%= event.creator.name %>)</div>
    <div class="event-location"><%= event.location %></div>
    <div class="btn btn-primary going"><%= link_to ((current_user.event_attendings.pluck(:event_id).include?event.id.to_i)? "Registered" : "Go?") , register_path(event.id), :method => :post %></div>
  </div>
  <div class="event event-description"><%= event.description %></div>
</div>

app/views/events/index.html.erb
<h2>Find a Great Event Today!</h2>

<div id="accordion">
	
  <h3>Upcoming Events (<%= @upcomingEvents.count %>)</h3>
  <div>
    <% @upcomingEvents.each do |e| %>
      <%= render partial: 'event', :locals => {:event => e} %>
    <% end %>
  </div>

  <h3>Past Events (<%= @pastEvents.count %>)</h3>
  <div>
    <% @pastEvents.each do |e| %>
      <%= render partial: 'event', :locals => {:event => e} %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <h2>Add a New Event</h2>
    <%= form_for(@event) do |f| %>  
    <div class="form-group row">  
      <%= f.label :name, :class => "col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :name, :class => "form-control"%>
      </div>
    </div>
    <div class="form-group row">  
      <%= f.label :location, :class => "col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :location, :class => "form-control" %>
      </div>
	</div>
	<div class="form-group row">
      <%= f.label :description, :class => "col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :description, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :date, :class => "col-sm-2" %>
      <div class="col-sm-10">
        <%= f.text_field :date, :class => ["datepicker", "form-control"] %>
      </div>
	</div>
	<div class="form-group row">
		<div class="col-sm-offset-2 col-sm-10">
          <%= f.submit "Create Event", :class => "btn btn-primary" %>
        </div>
	</div>	
	
    <% end %>
</div>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

<h2>Event Details</h2>

<%= render partial: 'event', :locals => {:event => @event} %>
<!--
<div class="event">
  <div>
    <div class="event-date"><%= @event.date.strftime("%b %e, %Y %T") %></div>
    <div class="event-name"><%= @event.name %></div>
    <div class="event-location"><%= @event.location %></div>
  </div>
  <div class="event event-description"><%= @event.description %></div>
</div>
-->
Event Name:  <%= @event.name %><%= tag(:br) %>
Date:  <%= @event.date %><%= tag(:br) %>
Location: <%= @event.location %><%= tag(:br) %>
Description: <%= @event.description %><%= tag(:br) %>

Created by: <%= @creator.name %><%= tag(:br) %>

Who's Coming?<%= tag(:br) %>
<ul>
<% @attendees.each do |attendee| %>
  <li>
  	<%= attendee.name %>
  </li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Private Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container">
<header class="row">
  <% unless current_user.nil? %>
	Welcome, <%= current_user.name %>
	
	<span>
		<%= link_to "[My Homepage]", user_path(current_user), method: :get %>		
    </span>
    
    <span>
    	<%= link_to "[View All Events]", events_index_path, method: :get %>
    </span>
    
    <span>
    	<% randomFriend = selectRandomUser %>
    	<%= link_to "[Where is #{randomFriend.name} Going?]", user_path(randomFriend), method: :get %>
    </span>
	
	<span>    	
    	<%= link_to "[Create an Event]", events_new_path, method: :get %>
    </span>
	
	<span class="logout">
    <%= link_to "Log out", logout_path, method: :delete %>
    </span>
  <% end %>
</header>
<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div>
  <div>
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<h2>Events</h2>
	<div id="accordion">
	  <h3><%= (@user == current_user)?("My"):(@user.name + "'s") %> Created Events (<%= @user.events.count %>)</h3>
	  <div>
		<% @user.events.each do |event| %>
	      <%= render partial: 'events/event', :locals => {:event => event} %>
	    <% end %>
	  </div>
	
	  <h3>Upcoming events (<%= @user.upcoming_events.count %>)</h3>
	  <div>
		<% @user.upcoming_events.each do |event| %>
		  <%= render partial: 'events/event', :locals => {:event => event} %>
		<% end %>
	  </div>
		
	  <h3>Previously attended events (<%= @user.previous_events.count %>)</h3>
	  <div>
		<% @user.previous_events.each do |event| %>
		  <%= render partial: 'events/event', :locals => {:event => event} %>
		<% end %>
	  </div>  
	</div>
</div>